@startuml
'https://plantuml.com/class-diagram

:HTTP based client for the Application:as HttpClient
:REST endpoints Layer (RestControllers): as RestControllersLayer
:Business Logic Layer (Process Request from Rest): as BusinessLayer
:Persistence Layer (Process Request from BusinessLogic): as PersistenceLayer

skinparam packageStyle node
package HttpClient {
}

skinparam packageStyle folder
package RestControllersLayer {
}

package BusinessLayer {
}

package PersistenceLayer {
}
note left of HttpClient : HttpClient which can make REST requests\nto Application's Controllers.
note left of RestControllersLayer : Controllers accept connection and call Facade\nUses request-data to call Business Layer Facade\nCall Business Layer through Facade.
note left of BusinessLayer : Prepare request to Persistence Layer\nCall Persistence Layer through Facade.
note left of PersistenceLayer : Prepare request to the Database\nCall Database feature through JPA.

HttpClient -> RestControllersLayer: http request
note top on link : HTTP request to Controllers Layer
RestControllersLayer -> BusinessLayer: call facade method
note top on link : JavaCall the method of Business Layer Facade
BusinessLayer -> PersistenceLayer: call facade method
note top on link : JavaCall the method of Persistence Layer Facade
PersistenceLayer ..> BusinessLayer: data as response to call
BusinessLayer ..> RestControllersLayer: response to call
RestControllersLayer ..> HttpClient: response to request

@enduml