[plantuml,MacroCommand.executeUndoNested.puml.png,png]
----
@startuml

participant CompositeCommand
participant CommandActionExecutor
participant CommandMessage
participant RootCommand
participant CommandExecutable

activate CompositeCommand
	CompositeCommand -> CompositeCommand : getActionExecutor
	activate CompositeCommand
		CompositeCommand --> CompositeCommand : CommandActionExecutor
	deactivate CompositeCommand
	CompositeCommand -> CommandActionExecutor : rollbackAction
	activate CommandActionExecutor
		CommandActionExecutor -> CommandActionExecutor : buildMessage
		activate CommandActionExecutor
			CommandActionExecutor --> CommandActionExecutor : CommandMessage
		deactivate CommandActionExecutor
		CommandActionExecutor -> CommandActionExecutor : processActionCommand
		activate CommandActionExecutor
			CommandActionExecutor -> CommandMessage : getContext
			activate CommandMessage
				CommandMessage --> CommandActionExecutor : Context
			deactivate CommandMessage
			CommandActionExecutor -> CommandMessage : getDirection
			activate CommandMessage
				CommandMessage --> CommandActionExecutor : CommandMessage$Direction
			deactivate CommandMessage
			CommandActionExecutor -> RootCommand : undoCommand
			activate RootCommand
				RootCommand -> CommandExecutable : executeUndo
				activate CommandExecutable
					CommandExecutable --> RootCommand : void
				deactivate CommandExecutable
				RootCommand --> CommandActionExecutor : void
			deactivate RootCommand
			CommandActionExecutor --> CommandActionExecutor : CommandMessage
		deactivate CommandActionExecutor
		CommandActionExecutor -> CommandMessage : getContext
		activate CommandMessage
			CommandMessage --> CommandActionExecutor : Context
		deactivate CommandMessage
		CommandActionExecutor --> CompositeCommand : Context
	deactivate CommandActionExecutor
deactivate CompositeCommand

@enduml

----