[plantuml,MacroCommand.createNestedContext.puml.png,png]
----
@startuml

participant CompositeCommand
participant PrepareNestedContextVisitor
participant RootCommand
participant Context

activate CompositeCommand
	CompositeCommand -> PrepareNestedContextVisitor : prepareContext
	activate PrepareNestedContextVisitor
		PrepareNestedContextVisitor -> RootCommand : createContext
		activate RootCommand
			RootCommand -> Context : setState
			activate Context
				Context --> RootCommand : void
			deactivate Context
			RootCommand -> Context : setState
			activate Context
				Context --> RootCommand : void
			deactivate Context
			RootCommand --> PrepareNestedContextVisitor : Context
		deactivate RootCommand
		PrepareNestedContextVisitor --> CompositeCommand : Context
	deactivate PrepareNestedContextVisitor
deactivate CompositeCommand

@enduml

----