[plantuml,RootCommand.undoCommand.puml.png,png]
----
@startuml

participant RootCommand
participant Context
participant CommandExecutable

activate RootCommand
	RootCommand -> Context : isDone
	activate Context
		Context --> RootCommand : boolean
	deactivate Context
	RootCommand -> RootCommand : self
	activate RootCommand
		RootCommand --> RootCommand : RootCommand
	deactivate RootCommand
	RootCommand -> CommandExecutable : executeUndo
	activate CommandExecutable
		CommandExecutable --> RootCommand : void
	deactivate CommandExecutable
	RootCommand -> RootCommand : afterRollback
	activate RootCommand
		RootCommand -> Context : setResult
		activate Context
			Context --> RootCommand : void
		deactivate Context
		RootCommand --> RootCommand : void
	deactivate RootCommand
deactivate RootCommand

@enduml

----