[plantuml,RootCommand.createContext.puml.png,png]
----
@startuml

participant CommandsFactory
participant RootCommand
participant CommandContext
participant Context

activate CommandsFactory
	CommandsFactory -> CommandsFactory : command
	activate CommandsFactory
		CommandsFactory --> CommandsFactory : RootCommand
	deactivate CommandsFactory
	CommandsFactory -> RootCommand : createContext
	activate RootCommand
		RootCommand -> CommandContext : builder
		activate CommandContext
			CommandContext --> RootCommand : CommandContext$CommandContextBuilder
		deactivate CommandContext
		RootCommand -> Context : setState
		activate Context
			Context --> RootCommand : void
		deactivate Context
		RootCommand -> Context : setState
		activate Context
			Context --> RootCommand : void
		deactivate Context
		RootCommand --> CommandsFactory : Context
	deactivate RootCommand
deactivate CommandsFactory

@enduml

----