[plantuml,SequentialCommandsTask.executeDoNestedSuccessful.puml.png,png]
----
@startuml

participant SequentialCommandsTask
participant Collection
participant Spliterators
participant Objects
participant StreamSupport
participant Stream
participant Collectors

activate SequentialCommandsTask
	SequentialCommandsTask -> Collection : stream
	activate Collection
		Collection -> Collection : spliterator
		activate Collection
			Collection -> Spliterators : spliterator
			activate Spliterators
				Spliterators -> Objects : requireNonNull
				activate Objects
					Objects --> Spliterators : Object
				deactivate Objects
				Spliterators --> Collection : Spliterator
			deactivate Spliterators
			Collection --> Collection : Spliterator
		deactivate Collection
		Collection -> StreamSupport : stream
		activate StreamSupport
			StreamSupport -> Objects : requireNonNull
			activate Objects
				Objects --> StreamSupport : Object
			deactivate Objects
			StreamSupport --> Collection : Stream
		deactivate StreamSupport
		Collection --> SequentialCommandsTask : Stream
	deactivate Collection
	SequentialCommandsTask -> Stream : map
	activate Stream
		Stream --> SequentialCommandsTask : Stream
	deactivate Stream
	SequentialCommandsTask -> Collectors : toCollection
	activate Collectors
		Collectors --> SequentialCommandsTask : Collector
	deactivate Collectors
	SequentialCommandsTask -> Stream : collect
	activate Stream
		Stream --> SequentialCommandsTask : Object
	deactivate Stream
deactivate SequentialCommandsTask

@enduml

----