[plantuml,SequentialCommands.cancelSequentialNestedCommandContext.puml.png,png]
----
@startuml

participant SequentialCommandsTask
participant Context

activate SequentialCommandsTask
	SequentialCommandsTask -> Context : getHistory
	activate Context
		Context --> SequentialCommandsTask : Context$LifeCycleHistory
	deactivate Context
	SequentialCommandsTask -> Context : setState
	activate Context
		Context --> SequentialCommandsTask : void
	deactivate Context
deactivate SequentialCommandsTask

@enduml

----