[plantuml,ApplicationAccessFacade.refreshCredentialsFor.puml.png,png]
----
@startuml

participant ApplicationAccessFacadeAdapter
participant JwtService
participant AccessTokensStorage
participant AccessCredentialsType

activate ApplicationAccessFacadeAdapter
	ApplicationAccessFacadeAdapter -> JwtService : isTokenExpired
	activate JwtService
		JwtService --> ApplicationAccessFacadeAdapter : boolean
	deactivate JwtService
	ApplicationAccessFacadeAdapter -> ApplicationAccessFacadeAdapter : refreshTokenIsExpired
	activate ApplicationAccessFacadeAdapter
		ApplicationAccessFacadeAdapter -> AccessTokensStorage : deleteCredentialsWithRefreshToken
		activate AccessTokensStorage
			AccessTokensStorage --> ApplicationAccessFacadeAdapter : void
		deactivate AccessTokensStorage
		ApplicationAccessFacadeAdapter --> ApplicationAccessFacadeAdapter : Optional
	deactivate ApplicationAccessFacadeAdapter
	ApplicationAccessFacadeAdapter -> ApplicationAccessFacadeAdapter : refreshedCredentials
	activate ApplicationAccessFacadeAdapter
		ApplicationAccessFacadeAdapter -> ApplicationAccessFacadeAdapter : extractUserName
		activate ApplicationAccessFacadeAdapter
			ApplicationAccessFacadeAdapter -> JwtService : extractUserName
			activate JwtService
				JwtService --> ApplicationAccessFacadeAdapter : String
			deactivate JwtService
			ApplicationAccessFacadeAdapter --> ApplicationAccessFacadeAdapter : String
		deactivate ApplicationAccessFacadeAdapter
		ApplicationAccessFacadeAdapter -> AccessTokensStorage : findCredentials
		activate AccessTokensStorage
			AccessTokensStorage --> ApplicationAccessFacadeAdapter : Optional
		deactivate AccessTokensStorage
		ApplicationAccessFacadeAdapter -> ApplicationAccessFacadeAdapter : rebuildCredentialsFor
		activate ApplicationAccessFacadeAdapter
			ApplicationAccessFacadeAdapter -> AccessCredentialsType : getUser
			activate AccessCredentialsType
				AccessCredentialsType --> ApplicationAccessFacadeAdapter : UserDetailsType
			deactivate AccessCredentialsType
			ApplicationAccessFacadeAdapter -> ApplicationAccessFacadeAdapter : grantCredentialsFor
			activate ApplicationAccessFacadeAdapter
				ApplicationAccessFacadeAdapter -> ApplicationAccessFacadeAdapter : buildFor
				activate ApplicationAccessFacadeAdapter
					ApplicationAccessFacadeAdapter --> ApplicationAccessFacadeAdapter : AccessCredentials
				deactivate ApplicationAccessFacadeAdapter
				ApplicationAccessFacadeAdapter --> ApplicationAccessFacadeAdapter : Optional
			deactivate ApplicationAccessFacadeAdapter
			ApplicationAccessFacadeAdapter --> ApplicationAccessFacadeAdapter : Optional
		deactivate ApplicationAccessFacadeAdapter
		ApplicationAccessFacadeAdapter --> ApplicationAccessFacadeAdapter : Optional
	deactivate ApplicationAccessFacadeAdapter
deactivate ApplicationAccessFacadeAdapter

@enduml

----