[plantuml,ApplicationAccessFacade.grantCredentialsFor.puml.png,png]
----
@startuml

participant ApplicationAccessFacadeAdapter
participant UserService

activate ApplicationAccessFacadeAdapter
	ApplicationAccessFacadeAdapter -> UserService : prepareUserDetails
	activate UserService
		UserService --> ApplicationAccessFacadeAdapter : Optional
	deactivate UserService
deactivate ApplicationAccessFacadeAdapter

@enduml

----