[plantuml,ApplicationAccessFacade.revokeCredentialsFor.puml.png,png]
----
@startuml

participant ApplicationAccessFacadeAdapter
participant AccessTokensStorage

activate ApplicationAccessFacadeAdapter
	ApplicationAccessFacadeAdapter -> AccessTokensStorage : findCredentials
	activate AccessTokensStorage
		AccessTokensStorage --> ApplicationAccessFacadeAdapter : Optional
	deactivate AccessTokensStorage
deactivate ApplicationAccessFacadeAdapter

@enduml

----