[plantuml,AuthenticationFacade.refresh.puml.png,png]
----
@startuml

participant AuthenticationFacadeImpl
participant ApplicationAccessFacade

activate AuthenticationFacadeImpl
	AuthenticationFacadeImpl -> ApplicationAccessFacade : refreshCredentialsFor
	activate ApplicationAccessFacade
		ApplicationAccessFacade --> AuthenticationFacadeImpl : Optional
	deactivate ApplicationAccessFacade
deactivate AuthenticationFacadeImpl

@enduml

----