[plantuml,DistributeAccessTokensStorage.findCredentials.puml.png,png]
----
@startuml

participant DistributeAccessTokensStorage
participant Objects
participant Optional
participant Map

activate DistributeAccessTokensStorage
	DistributeAccessTokensStorage -> Objects : isNull
	activate Objects
		Objects --> DistributeAccessTokensStorage : boolean
	deactivate Objects
	DistributeAccessTokensStorage -> Optional : empty
	activate Optional
		Optional --> DistributeAccessTokensStorage : Optional
	deactivate Optional
	DistributeAccessTokensStorage -> Map : get
	activate Map
		Map --> DistributeAccessTokensStorage : Object
	deactivate Map
	DistributeAccessTokensStorage -> Optional : ofNullable
	activate Optional
		Optional --> DistributeAccessTokensStorage : Optional
	deactivate Optional
deactivate DistributeAccessTokensStorage

@enduml

----