[plantuml,DistributeAccessTokensStorage.deleteCredentialsWithRefreshToken.puml.png,png]
----
@startuml

participant DistributeAccessTokensStorage
participant Cache
participant CacheCollection
participant CacheStream
participant Objects
participant Stream
participant Optional
participant Consumer

activate DistributeAccessTokensStorage
	DistributeAccessTokensStorage -> Cache : values
	activate Cache
		Cache --> DistributeAccessTokensStorage : CacheCollection
	deactivate Cache
	DistributeAccessTokensStorage -> CacheCollection : stream
	activate CacheCollection
		CacheCollection --> DistributeAccessTokensStorage : CacheStream
	deactivate CacheCollection
	DistributeAccessTokensStorage -> CacheStream : filter
	activate CacheStream
		CacheStream -> CacheStream : filter
		activate CacheStream
			CacheStream --> CacheStream : CacheStream
		deactivate CacheStream
		CacheStream --> DistributeAccessTokensStorage : CacheStream
	deactivate CacheStream
	DistributeAccessTokensStorage -> Objects : requireNonNull
	activate Objects
		Objects --> DistributeAccessTokensStorage : Object
	deactivate Objects
	DistributeAccessTokensStorage -> CacheStream : map
	activate CacheStream
		CacheStream -> CacheStream : map
		activate CacheStream
			CacheStream --> CacheStream : CacheStream
		deactivate CacheStream
		CacheStream --> DistributeAccessTokensStorage : CacheStream
	deactivate CacheStream
	DistributeAccessTokensStorage -> CacheStream : map
	activate CacheStream
		CacheStream -> CacheStream : map
		activate CacheStream
			CacheStream --> CacheStream : CacheStream
		deactivate CacheStream
		CacheStream --> DistributeAccessTokensStorage : CacheStream
	deactivate CacheStream
	DistributeAccessTokensStorage -> Stream : findFirst
	activate Stream
		Stream --> DistributeAccessTokensStorage : Optional
	deactivate Stream
	DistributeAccessTokensStorage -> Optional : ifPresent
	activate Optional
		Optional -> Consumer : accept
		activate Consumer
			Consumer --> Optional : void
		deactivate Consumer
		Optional --> DistributeAccessTokensStorage : void
	deactivate Optional
deactivate DistributeAccessTokensStorage

@enduml

----