[plantuml,DistributeAccessTokensStorage.deleteCredentials.puml.png,png]
----
@startuml

participant DistributeAccessTokensStorage
participant Cache

activate DistributeAccessTokensStorage
	DistributeAccessTokensStorage -> Cache : evict
	activate Cache
		Cache --> DistributeAccessTokensStorage : void
	deactivate Cache
deactivate DistributeAccessTokensStorage

@enduml

----