[plantuml,JwtService.isTokenValid.puml.png,png]
----
@startuml

participant JwtServiceImpl
participant Jwts
participant UserDetails

activate JwtServiceImpl
	JwtServiceImpl -> JwtServiceImpl : extractUserName
	activate JwtServiceImpl
		JwtServiceImpl -> JwtServiceImpl : extractClaim
		activate JwtServiceImpl
			JwtServiceImpl -> JwtServiceImpl : extractAllClaims
			activate JwtServiceImpl
				JwtServiceImpl -> Jwts : parser
				activate Jwts
					Jwts --> JwtServiceImpl : JwtParserBuilder
				deactivate Jwts
				JwtServiceImpl --> JwtServiceImpl : Claims
			deactivate JwtServiceImpl
			JwtServiceImpl --> JwtServiceImpl : Object
		deactivate JwtServiceImpl
		JwtServiceImpl --> JwtServiceImpl : String
	deactivate JwtServiceImpl
	JwtServiceImpl -> UserDetails : getUsername
	activate UserDetails
		UserDetails --> JwtServiceImpl : String
	deactivate UserDetails
deactivate JwtServiceImpl

@enduml

----