[plantuml,LocalAccessTokensStorage.deleteCredentialsWithRefreshToken.puml.png,png]
----
@startuml

participant LocalAccessTokensStorage
participant Map
participant Collection
participant Objects
participant Optional
participant Consumer

activate LocalAccessTokensStorage
	LocalAccessTokensStorage -> Map : values
	activate Map
		Map --> LocalAccessTokensStorage : Collection
	deactivate Map
	LocalAccessTokensStorage -> Collection : stream
	activate Collection
		Collection -> Collection : spliterator
		activate Collection
			Collection --> Collection : Spliterator
		deactivate Collection
		Collection --> LocalAccessTokensStorage : Stream
	deactivate Collection
	LocalAccessTokensStorage -> Objects : requireNonNull
	activate Objects
		Objects --> LocalAccessTokensStorage : Object
	deactivate Objects
	LocalAccessTokensStorage -> Optional : ifPresent
	activate Optional
		Optional -> Consumer : accept
		activate Consumer
			Consumer --> Optional : void
		deactivate Consumer
		Optional --> LocalAccessTokensStorage : void
	deactivate Optional
deactivate LocalAccessTokensStorage

@enduml

----