[plantuml,LocalAccessTokensStorage.findCredentials.puml.png,png]
----
@startuml

participant LocalAccessTokensStorage
participant Optional
participant Map

activate LocalAccessTokensStorage
	LocalAccessTokensStorage -> Optional : empty
	activate Optional
		Optional --> LocalAccessTokensStorage : Optional
	deactivate Optional
	LocalAccessTokensStorage -> Map : get
	activate Map
		Map --> LocalAccessTokensStorage : Object
	deactivate Map
	LocalAccessTokensStorage -> Optional : ofNullable
	activate Optional
		Optional --> LocalAccessTokensStorage : Optional
	deactivate Optional
deactivate LocalAccessTokensStorage

@enduml

----