[plantuml,LocalAccessTokensStorage.deleteCredentials.puml.png,png]
----
@startuml

participant LocalAccessTokensStorage
participant Optional
participant Map
participant Consumer

activate LocalAccessTokensStorage
	LocalAccessTokensStorage -> LocalAccessTokensStorage : findCredentials
	activate LocalAccessTokensStorage
		LocalAccessTokensStorage -> Optional : empty
		activate Optional
			Optional --> LocalAccessTokensStorage : Optional
		deactivate Optional
		LocalAccessTokensStorage -> Map : get
		activate Map
			Map --> LocalAccessTokensStorage : Object
		deactivate Map
		LocalAccessTokensStorage -> Optional : ofNullable
		activate Optional
			Optional --> LocalAccessTokensStorage : Optional
		deactivate Optional
		LocalAccessTokensStorage --> LocalAccessTokensStorage : Optional
	deactivate LocalAccessTokensStorage
	LocalAccessTokensStorage -> Optional : ifPresent
	activate Optional
		Optional -> Consumer : accept
		activate Consumer
			Consumer --> Optional : void
		deactivate Consumer
		Optional --> LocalAccessTokensStorage : void
	deactivate Optional
deactivate LocalAccessTokensStorage

@enduml

----