[plantuml,BusinessLogicFacades.puml.png,png]
----
@startuml
!pragma layout smetana

interface AuthorityPersonFacade {
	{field} {static} +ACTION_IDS : List
	{field} {static} +CREATE_MACRO : String
	{field} {static} +CREATE_OR_UPDATE : String
	{field} {static} +DELETE : String
	{field} {static} +DELETE_MACRO : String
	{field} {static} +FIND_ALL : String
	{field} {static} +FIND_BY_ID : String
	{field} {static} +LOGIN : String
	{field} {static} +LOGOUT : String
	{field} {static} +SUBSPACE : String
	{method} +getName () : String
	{method} +validActions () : List
}


interface BusinessFacade {
	{method} +decodeLongArgument ( parameters : Object[] ) : Long
	{method} +decodeStringArgument ( parameters : Object[] ) : String
	{method} +doActionAndResult ( actionId : String , parameters : Object[] ) : Object
	{method}  {abstract} +getName () : String
	{method} +isInvalid ( item : BaseType ) : boolean
	{method} +throwInvalidActionId ( actionId : String ) : void
	{method} +validActions () : List
}


interface CoursesFacade {
	{field} {static} +ACTION_IDS : List
	{field} {static} +CREATE_OR_UPDATE : String
	{field} {static} +DELETE : String
	{field} {static} +FIND_BY_ID : String
	{field} {static} +FIND_NOT_REGISTERED : String
	{field} {static} +FIND_REGISTERED : String
	{field} {static} +REGISTER : String
	{field} {static} +SUBSPACE : String
	{field} {static} +UN_REGISTER : String
	{method} +getName () : String
	{method} +validActions () : List
}


interface EducationFacade {
	{field} {static} +NAMESPACE : String
	{method} +doActionAndResult ( actionId : String , parameters : Object[] ) : Object
	{method} +educationAction ( actionId : String , parameters : Object[] ) : Object
	{method} +throwsUnknownActionId ( actionId : String ) : Function
}


interface FacultyFacade {
	{field} {static} +ACTION_IDS : List
	{field} {static} +CREATE_OR_UPDATE : String
	{field} {static} +DELETE : String
	{field} {static} +FIND_ALL : String
	{field} {static} +FIND_BY_ID : String
	{field} {static} +SUBSPACE : String
	{method} +getName () : String
	{method} +validActions () : List
}


interface OrganizationFacade {
	{field} {static} +NAMESPACE : String
	{method} +doActionAndResult ( actionId : String , parameters : Object[] ) : Object
	{method} +organizationAction ( actionId : String , parameters : Object[] ) : Object
	{method} +throwsUnknownActionId ( actionId : String ) : Function
}


interface PersonProfileFacade {
	{field} {static} +NAMESPACE : String
	{method}  {abstract} +createOrUpdateActionId () : String
	{method}  {abstract} +deleteByIdActionId () : String
	{method} +doActionAndResult ( actionId : String , parameters : Object[] ) : Object
	{method}  {abstract} +findByIdActionId () : String
	{method}  {abstract} +personProfileAction ( actionId : String , parameters : Object[] ) : Object
}


interface PrincipalProfileFacade {
	{field} {static} +ACTION_IDS : List
	{field} {static} +CREATE_OR_UPDATE : String
	{field} {static} +DELETE_BY_ID : String
	{field} {static} +FIND_BY_ID : String
	{field} {static} +SUBSPACE : String
	{method} +createOrUpdateActionId () : String
	{method} +deleteByIdActionId () : String
	{method} +findByIdActionId () : String
	{method} +getName () : String
	{method} +validActions () : List
}


interface StudentProfileFacade {
	{field} {static} +ACTION_IDS : List
	{field} {static} +CREATE_OR_UPDATE : String
	{field} {static} +DELETE_BY_ID : String
	{field} {static} +FIND_BY_ID : String
	{field} {static} +SUBSPACE : String
	{method} +createOrUpdateActionId () : String
	{method} +deleteByIdActionId () : String
	{method} +findByIdActionId () : String
	{method} +getName () : String
	{method} +validActions () : List
}


interface StudentsFacade {
	{field} {static} +ACTION_IDS : List
	{field} {static} +CREATE_MACRO : String
	{field} {static} +CREATE_OR_UPDATE : String
	{field} {static} +DELETE : String
	{field} {static} +DELETE_MACRO : String
	{field} {static} +FIND_BY_ID : String
	{field} {static} +FIND_ENROLLED : String
	{field} {static} +FIND_NOT_ENROLLED : String
	{field} {static} +SUBSPACE : String
	{method} +getName () : String
	{method} +validActions () : List
}


interface StudentsGroupFacade {
	{field} {static} +ACTION_IDS : List
	{field} {static} +CREATE_OR_UPDATE : String
	{field} {static} +DELETE : String
	{field} {static} +FIND_ALL : String
	{field} {static} +FIND_BY_ID : String
	{field} {static} +SUBSPACE : String
	{method} +getName () : String
	{method} +validActions () : List
}




AuthorityPersonFacade ..|>  OrganizationFacade
CoursesFacade ..|>  EducationFacade
EducationFacade ..|>  BusinessFacade
FacultyFacade ..|>  OrganizationFacade
OrganizationFacade ..|>  BusinessFacade
PersonProfileFacade ..|>  BusinessFacade
PrincipalProfileFacade ..|>  PersonProfileFacade
StudentProfileFacade ..|>  PersonProfileFacade
StudentsFacade ..|>  EducationFacade
StudentsGroupFacade ..|>  OrganizationFacade


@enduml
----