[plantuml,CommonDataModel.puml.png,png]
----
@startuml
!pragma layout smetana

interface AccessCredentials {
	{method} +getId () : Long
	{method}  {abstract} +getRefreshToken () : String
	{method}  {abstract} +getToken () : String
}


interface AuthorityPerson {
	{method}  {abstract} +getFaculties () : List
	{method} +getFullName () : String
	{method}  {abstract} +getTitle () : String
}


interface BaseType {
	{method}  {abstract} +getId () : Long
}


interface Course {
	{method}  {abstract} +getDescription () : String
	{method}  {abstract} +getName () : String
	{method}  {abstract} +getStudents () : List
}


enum ExtraKey {
	{field} +FACEBOOK
	{field} +INSTAGRAM
	{field} +LINKEDIN
	{field} +TELEGRAM
	{field} +WEB
	{field} +YOUTUBE
}


interface Faculty {
	{method}  {abstract} +getCourses () : List
	{method}  {abstract} +getDean () : AuthorityPerson
	{method}  {abstract} +getName () : String
}


enum Permission {
	{field} +Permission:Can create new instances of AuthorityPersons
	{field} +Permission:Can create new instances of Faculties or StudentsGroups
	{field} +Permission:Can create new instances of Students or Courses
	{field} +Permission:Can get the instance of AuthorityPerson, Faculty or StudentsGroup
	{field} +Permission:Can get the instance of Profile
	{field} +Permission:Can get the instance of Student or Course
	{field} +Permission:Can look for AuthorityPersons, Faculties or StudentsGroups
	{field} +Permission:Can look for Students or Courses
	{field} +Permission:Can remove the instance of AuthorityPerson, Faculty or StudentsGroup
	{field} +Permission:Can remove the instance of Student or Course
	{field} +Permission:Can update the instance of AuthorityPerson, Faculty or StudentsGroup
	{field} +Permission:Can update the instance of Profile
	{field} +Permission:Can update the instance of Student or Course
}


interface Person {
	{method}  {abstract} +getFirstName () : String
	{method}  {abstract} +getGender () : String
	{method}  {abstract} +getLastName () : String
	{method} +getProfileId () : Long
}


interface PersonProfile {
	{method}  {abstract} +getEmail () : String
	{method} +getExtra ( key : ExtraKey ) : Optional
	{method}  {abstract} +getExtra ( key : String ) : Optional
	{method}  {abstract} +getExtraKeys () : String[]
	{method}  {abstract} +getLocation () : String
	{method}  {abstract} +getPhone () : String
	{method}  {abstract} +getPhotoUrl () : String
}


interface PrincipalProfile {
}


enum Role {
	{field} +The staff role: School Deputy Principal
	{field} +The staff role: School Head Teacher
	{field} +The staff role: School Principal
	{field} +The staff role: School Support Staff
	{field} +The staff role: School Teacher
}


interface SchoolAccess {
	{method}  {abstract} +getPermissions () : Set
	{method}  {abstract} +getRole () : Role
	{method}  {abstract} +getUsername () : String
	{method} +isPassword ( password : String ) : boolean
	{method} +makeSignatureFor ( password : String ) : String
}


interface Student {
	{method}  {abstract} +getCourses () : List
	{method}  {abstract} +getDescription () : String
	{method} +getFullName () : String
}


interface StudentProfile {
}


interface StudentsGroup {
	{method}  {abstract} +getLeader () : Student
	{method}  {abstract} +getName () : String
	{method}  {abstract} +getStudents () : List
}




AccessCredentials ..|>  BaseType
AuthorityPerson ..|>  Person
Course ..|>  BaseType
Faculty ..|>  BaseType
Person ..|>  BaseType
PersonProfile ..|>  BaseType
PrincipalProfile ..|>  PersonProfile
PrincipalProfile ..|>  SchoolAccess
Student ..|>  Person
StudentProfile ..|>  PersonProfile
StudentsGroup ..|>  BaseType


@enduml
----