= Application Business Logic Module
Doc Writer <oleg.sopilnyak@gmail.com>
:doctype: article
:toc: left
:toclevels: 4
:sectnums:
:source-highlighter: rouge
:imagesdir: ./images
:tab: {nbsp}{nbsp}{nbsp}{nbsp}

== Intro
{tab}The *Module* is implementing main *Business Logic* of the *Application*. The *_Ingress Module_* _stuff_ is communicating with it through *BusinessFacades* Set. The implementation in module is executing particular *Action* in order to implement the *Application*'s feature. Each *Action* is executing in the *ActionContext*.

.**Ingress Module**'s the Interaction through Stuff
include::../puml/class-diagrams/ActionContextStuff.puml[]
{tab}The Controller of *ingress module* launches *Action* through the particular *Business Facade* according to the feature's *Domain*.

.Business Facades by Application's *Domains*
[%collapsible]
====
{tab}{tab}{tab} *Note!* +
{tab}Concrete *actionId* values are declared in the particular facade. +
The *Action* is executing using `doActionAndResult(actionId , actionParameters)` using particular *BusinessFacade* implementation.

.Business Facades Set Declaration from *micro-core* Module
include::../puml/class-diagrams/BusinessLogicFacades.puml[]

.Business Facades Set Implementation
include::../puml/class-diagrams/BusinessFacadesModel.puml[]
====

== Module parts

=== The Model
{tab}The Business Logic *Action* execution is going through *CommandActionExecutor* Service

.BusinessFacade *Action* through *CommandMessage* Architecture
[%collapsible]
====
* `commitAction(actionContext , commandContext)` for *DO* Action Type
* `rollbackAction(actionContext , commandContext)` for *UNDO* Action Type

Both of them are executing through `processActionCommand(commandMessage)` of the Service.

.Business Action Execution Architecture
include::../puml/class-diagrams/CoreExecutableCommandImplementationModel.puml[]

Current implementation is built on the command messages queues.
Here is used *MessageExchange* (implemented in *CommandMessagesExchangeExecutorAdapter*) service +
and *MessagesProcessor* for these purposes.

'''
Business Action Command Message Architecture

.*CommandMessage* of the Action
include::../puml/class-diagrams/CoreExecutableCommandMessageModel.puml[]
'''
====

{tab}Each operational data type from outside the Module is passing through *Model Data Mapper* adopting it to the operational data model of the Module.

.Business Action Operational Data Model
[%collapsible]
====

.Outside Data Model Mapper
include::../puml/class-diagrams/BusinessExecutableMessageMapperModel.puml[]

.Operational Data Model
include::../puml/class-diagrams/BusinessExecutableCommandMessageModel.puml[]

'''
====

.Basic Command Architecture
[%collapsible]
====

.Core Commands Architecture
include::../puml/class-diagrams/CoreCommandModel.puml[]
'''

.Core Nested Commands Architecture (uses in *CompositeCommand*, please see above)
include::../puml/class-diagrams/CoreNestedCommandModel.puml[]
'''

.Advanced Commands Implementation Architecture
include::../puml/class-diagrams/CoreCommandImplementationModel.puml[]
'''

.The Commands According to the *Action Domain*
include::../puml/class-diagrams/CommonCommandModel.puml[]
====
'''

=== Business Logic Action Execution
{tab}To execute BusinessLogic Action is used *CommandActionExecutor* which uses application's *Command* which ID is the same as target action's ID, using *CommandMessage* as an action execution context carrier. +
Business Action Request is passing through *ActionFacade*, getting command-context and command-instance from the *CommandsFactory*, preparing *CommandMessage* and passing it to the *CommandActionExecutor*

.Action Message Execution
[%collapsible]
====
.Business Logic Do Action And Get Result Sequence
include::../puml/sequence-diagrams/BusinessFacade.doActionAndResult.puml[]

.CommandActionExecutor.processActionCommand Sequence
include::../puml/sequence-diagrams/CommandActionExecutor.processActionCommand.puml[]

.CommandThroughMessagesExecutor.processActionCommand Sequence
include::../puml/sequence-diagrams/CommandMessagesExchangeExecutorAdapter.processActionCommand.puml[]
====

.Action Command Execution
[%collapsible]
====
.Business Logic Execute MessageAction Sequence
include::../puml/sequence-diagrams/ActionFacade.executeCommand.puml[]

.Business Logic Execute MessageAction Sequence
include::../puml/sequence-diagrams/CommandActionExecutor.processMessageAction.puml[]
====
'''

=== Command Execution Universe
==== Core Command Execution
{tab}As you understood, there is no *Action* entity here, *Command* entity is used instead. The *Command* entity here isn't exact implementation of the `Command Design Pattern` because for each business logic action's request, new instance of the *Command* didn't create. #Instead#, each action execution creates `command context` in order to use it with particular command instance. +

.CommandContext Architecture
include::../puml/class-diagrams/CommandContext.Model.puml[]
. `command -` reference to the instance of *Command* where the *Context* will be executed
. `redoParameter -` input parameter value for the *Command* execution
. `undoParameter -` input parameter value for the *Command* execution rollback
. `result -` the *result value* of the *Command* execution
. `state -` the current *state* of the *Command* execution (*INIT|READY|WORK|DONE|FAIL|CANCEL|UNDONE*)

. `exception -` the *cause* of failed *Command* execution
. `startedAt -` *when* was started the *Command* execution
. `duration -` *how long* was lasted the *Command* execution

In that case *Command* entity behavior closer to `Strategy Design Pattern`.

.Command Execution Behavior
[%collapsible]
====
* First of all *ActionExecutor* creates the Command Context

.CommandFactory.makeCommandContext Sequence
include::../puml/sequence-diagrams/RootCommand.createContext.puml[]

* Then it passes built context to the *Command* instance for execution

.Command.doCommand Sequence
include::../puml/sequence-diagrams/RootCommand.doCommand.puml[]

.Command.doCommand Activity Diagram
include::../puml/sequence-diagrams/RootCommand.doLifeCycle.puml[]
====

{tab}Concrete implementation of the *Command*, usually is connected to the external world using injected external access facades (*Persistence Facade* for example) which allows Command's execution to change or retrieve data of the Database or any other DataSources(Messaging or RPC). +
{tab}Each *Command* which affecting external data during execution *should* prepare data-set and store it into Context (`undoParameter`) for correct Command's rollback process (to keep external data integrity).

.Command Execution Rollback Behavior
[%collapsible]
====
.Command.undoCommand Sequence
include::../puml/sequence-diagrams/RootCommand.undoCommand.puml[]

.Command.undoCommand Activity Diagram
include::../puml/sequence-diagrams/RootCommand.undoLifeCycle.puml[]
====

==== Composite Command Execution
{tab}The *Composite Command* entity is still the *Command* but has some different behavior in compare. The *Composite Command* usually doesn't interact with external world, delegating it to the `nested` *Commands*. There is no big difference between *RootCommand* and *CompositeCommand* context making. Only input parameter of the command execution `redoParameter -` uses special parameter type (*MacroCommandParameter*).

.MacroCommand Architecture
include::../puml/class-diagrams/MacroCommand.Model.puml[]

{tab}Which contains the nested command-contexts ordered the same way as it is in CompositeCommand's nested commands list. If something went wrong with nested-command execution during *CompositeCommand* execution then all nested commands will be rolling back (`Command.undoCommand`).That way it's implementing well known `*Saga* Design Pattern`.

.Composite Command Making Context
[%collapsible]
====
.CompositeCommand.createContext Sequence
include::../puml/sequence-diagrams/MacroCommand.createContext.puml[]

.CompositeCommand.createNestedContext Sequence
include::../puml/sequence-diagrams/MacroCommand.createNestedContext.puml[]

{tab}The nested command context creation process is going through special visitor to address it to the correct place.

.CompositeCommand.acceptPreparedContext Visitor
include::../puml/class-diagrams/MacroCommand.Context.Visitor.puml[]

{tab}Any method of which can be overridden in the children of *MacroCommand* in order to change standard behavior for particular type of the nested-command's context creation.

'''
====

.Composite Command Execution
[%collapsible]
====

.CompositeCommand.executeDo Activity Diagram
include::../puml/sequence-diagrams/MacroCommand.doLifeCycle.puml[]

{tab}After nested commands execution finalizing execution results.

.MacroCommand.afterExecutionProcessing Sequence
include::../puml/sequence-diagrams/MacroCommand.afterExecutionProcessing.puml[]

'''
====
{tab}The main goal of the composite rollback is to restore affected external data. As it mentioned before it's doing through *Command.undoCommand(context)* for each nested command which context is in *Done* state.

.Composite Command Execution Rollback
[%collapsible]
====

.CompositeCommand.executeUndo Activity Diagram
include::../puml/sequence-diagrams/MacroCommand.undoLifeCycle.puml[]

====
'''
==== Advanced Composite Command
{tab}There are two special children types of `MacroCommand` +
`SequentialCommandsTask` and `ParallelCommandsTask` +

.Advanced MacroCommand Architecture
include::../puml/class-diagrams/MacroCommand.Advanced.Model.puml[]

each ot them has the changed behavior of nested command processing [ *executeNested(contexts)* and *rollbackNested(contexts)* ]. +
{tab}As you can guess `SequentialCommandsTask` is processing nested commands in sequential way instead of `ParallelCommandsTask` which doing it in parallel one. +
{tab}The extra option of `SequentialCommandsTask` is possibility to transfer result of nested-command execution to the next nested one which is going to be executed.

{tab}{tab} *Sequential Task Execution* +
Each command from *the nest* is executing one by one till end of the nest is reached or wrong command execution detected.

.SequentialCommandsTask.executeDoNested Sequence
include::../puml/sequence-diagrams/SequentialCommands.doSequentialNestedCommand.puml[]

If wrong command execution is detected the rest of nested ones will be not executing just canceled (*context.state=CANCEL*).

.SequentialCommandsTask.cancelExecuteDoNested Sequence
include::../puml/sequence-diagrams/SequentialCommands.cancelSequentialNestedCommandContext.puml[]

{tab}{tab} *Parallel Task Execution* +
All command from *the nest* is executing simultaneously in separated threads and waiting for all threads. All rolled back contexts is storing to `context.undoParameter` for further rollback of rollback action when rollback went wrong. Sounds crazy but it is. +
{tab}{tab} *Parallel Task Execution Rollback* +
All command from *the nest* is executing simultaneously in separated threads and waiting for all threads.

'''

=== Commands Factories
{tab}The commands factories in commands universe playing two main roles:

* union commands by command types (*Abstract Factory*)
* building command-context before action's execution (*Builder*).

.Commands Factory Architecture
[%collapsible]
====
.Architecture
include::../puml/class-diagrams/CommandsFactory.Model.puml[]
====

During boot application starting *Spring* scans particular package of *Java classes* `@ComponentScan("oleg.sopilnyak.test.service.command.executable")`

.Command.doCommand Activity Diagram
include::../puml/class-diagrams/CommandsFactory.Configuration.Model.puml[]
and distributing found commands among *CommandsFactory* instances according the *Command* type. +
{tab}Then it's possible to get *Command* instance by command ID from particular *CommandsFactory*. To support correct *JSON* deserialization of *CommandContext* was designed and developed *CommandsFactoriesFarm* which union all *CommandsFactory* instances. Farm can be used in any place of the module to do something not related to particular *Command* type.

.Commands Factories Farm Architecture
[%collapsible]
====
.Architecture
include::../puml/class-diagrams/CommandsFactoriesFarm.Model.puml[]
====

