[plantuml,StudentsGroupFacade.deleteStudentsGroup.puml.png,png]
----
@startuml

participant StudentsGroupFacade
participant OrganizationFacade
participant BaseType

activate StudentsGroupFacade
	StudentsGroupFacade -> OrganizationFacade : isInvalid
	activate OrganizationFacade
		OrganizationFacade -> BaseType : getId
		activate BaseType
			BaseType --> OrganizationFacade : Long
		deactivate BaseType
		OrganizationFacade --> StudentsGroupFacade : boolean
	deactivate OrganizationFacade
	StudentsGroupFacade -> BaseType : getId
	activate BaseType
		BaseType --> StudentsGroupFacade : Long
	deactivate BaseType
	StudentsGroupFacade -> StudentsGroupFacade : deleteStudentsGroupById
	activate StudentsGroupFacade
		StudentsGroupFacade --> StudentsGroupFacade : void
	deactivate StudentsGroupFacade
deactivate StudentsGroupFacade

@enduml

----