[plantuml,AuthorityPersonFacade.deleteAuthorityPerson.puml.png,png]
----
@startuml

participant AuthorityPersonFacade
participant OrganizationFacade
participant BaseType

activate AuthorityPersonFacade
	AuthorityPersonFacade -> OrganizationFacade : isInvalid
	activate OrganizationFacade
		OrganizationFacade -> BaseType : getId
		activate BaseType
			BaseType --> OrganizationFacade : Long
		deactivate BaseType
		OrganizationFacade --> AuthorityPersonFacade : boolean
	deactivate OrganizationFacade
	AuthorityPersonFacade -> BaseType : getId
	activate BaseType
		BaseType --> AuthorityPersonFacade : Long
	deactivate BaseType
	AuthorityPersonFacade -> AuthorityPersonFacade : deleteAuthorityPersonById
	activate AuthorityPersonFacade
		AuthorityPersonFacade --> AuthorityPersonFacade : void
	deactivate AuthorityPersonFacade
deactivate AuthorityPersonFacade

@enduml

----