[plantuml,PersonProfileFacade.EntryPoint.puml.png,png]
----
@startuml

participant PersonProfileFacade

activate PersonProfileFacade
	PersonProfileFacade -> PersonProfileFacade : personProfileAction
	activate PersonProfileFacade
		PersonProfileFacade --> PersonProfileFacade : Object
	deactivate PersonProfileFacade
deactivate PersonProfileFacade

@enduml

----