[plantuml,PersonProfileFacade.delete.puml.png,png]
----
@startuml

participant PersonProfileFacade
participant PersistenceFacadeUtilities
participant BaseType

activate PersonProfileFacade
	PersonProfileFacade -> PersistenceFacadeUtilities : isInvalid
	activate PersistenceFacadeUtilities
		PersistenceFacadeUtilities -> BaseType : getId
		activate BaseType
			BaseType --> PersistenceFacadeUtilities : Long
		deactivate BaseType
		PersistenceFacadeUtilities -> PersistenceFacadeUtilities : isInvalidId
		activate PersistenceFacadeUtilities
			PersistenceFacadeUtilities --> PersistenceFacadeUtilities : boolean
		deactivate PersistenceFacadeUtilities
		PersistenceFacadeUtilities --> PersonProfileFacade : boolean
	deactivate PersistenceFacadeUtilities
	PersonProfileFacade -> BaseType : getId
	activate BaseType
		BaseType --> PersonProfileFacade : Long
	deactivate BaseType
	PersonProfileFacade -> PersonProfileFacade : deleteById
	activate PersonProfileFacade
		PersonProfileFacade --> PersonProfileFacade : void
	deactivate PersonProfileFacade
deactivate PersonProfileFacade

@enduml

----