[plantuml,Education.Courses.findEmptyCourses.puml.png,png]
----
@startuml

participant CoursesRestController
participant CoursesFacade

activate CoursesRestController
	CoursesRestController -> CoursesFacade : findWithoutStudents
	activate CoursesFacade
		CoursesFacade --> CoursesRestController : Set
	deactivate CoursesFacade
	CoursesRestController -> CoursesRestController : resultToDto
	activate CoursesRestController
		CoursesRestController --> CoursesRestController : List
	deactivate CoursesRestController
deactivate CoursesRestController

@enduml

----