[plantuml,Education.Courses.updateCourse.puml.png,png]
----
@startuml

participant CoursesRestController
participant BaseDto
participant EducationFacade
participant EndpointMapper

activate CoursesRestController
	CoursesRestController -> BaseDto : getId
	activate BaseDto
		BaseDto --> CoursesRestController : Long
	deactivate BaseDto
	CoursesRestController -> CoursesRestController : isInvalid
	activate CoursesRestController
		CoursesRestController --> CoursesRestController : boolean
	deactivate CoursesRestController
	CoursesRestController -> CoursesRestController : createOrUpdate
	activate CoursesRestController
		CoursesRestController -> EducationFacade : doActionAndResult
		activate EducationFacade
			EducationFacade -> EducationFacade : educationAction
			activate EducationFacade
				EducationFacade --> EducationFacade : Object
			deactivate EducationFacade
			EducationFacade --> CoursesRestController : Object
		deactivate EducationFacade
		CoursesRestController --> CoursesRestController : Optional
	deactivate CoursesRestController
	CoursesRestController -> CoursesRestController : resultToDto
	activate CoursesRestController
		CoursesRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> CoursesRestController : CourseDto
		deactivate EndpointMapper
		CoursesRestController --> CoursesRestController : CourseDto
	deactivate CoursesRestController
deactivate CoursesRestController

@enduml

----