[plantuml,Education.RegisterCourse.registerToCourse.puml.png,png]
----
@startuml

participant RegisterCourseController
participant StudentsFacade
participant CoursesFacade
participant BaseType

activate RegisterCourseController
	RegisterCourseController -> RegisterCourseController : restoreEntity
	activate RegisterCourseController
		RegisterCourseController -> StudentsFacade : findById
		activate StudentsFacade
			StudentsFacade --> RegisterCourseController : Optional
		deactivate StudentsFacade
		RegisterCourseController --> RegisterCourseController : Student
	deactivate RegisterCourseController
	RegisterCourseController -> RegisterCourseController : restoreEntity
	activate RegisterCourseController
		RegisterCourseController -> CoursesFacade : findById
		activate CoursesFacade
			CoursesFacade --> RegisterCourseController : Optional
		deactivate CoursesFacade
		RegisterCourseController --> RegisterCourseController : Course
	deactivate RegisterCourseController
	RegisterCourseController -> BaseType : getId
	activate BaseType
		BaseType --> RegisterCourseController : Long
	deactivate BaseType
	RegisterCourseController -> BaseType : getId
	activate BaseType
		BaseType --> RegisterCourseController : Long
	deactivate BaseType
	RegisterCourseController -> CoursesFacade : register
	activate CoursesFacade
		CoursesFacade -> CoursesFacade : isInvalid
		activate CoursesFacade
			CoursesFacade -> BaseType : getId
			activate BaseType
				BaseType --> CoursesFacade : Long
			deactivate BaseType
			CoursesFacade --> CoursesFacade : boolean
		deactivate CoursesFacade
		CoursesFacade -> CoursesFacade : isInvalid
		activate CoursesFacade
			CoursesFacade -> BaseType : getId
			activate BaseType
				BaseType --> CoursesFacade : Long
			deactivate BaseType
			CoursesFacade --> CoursesFacade : boolean
		deactivate CoursesFacade
		CoursesFacade -> BaseType : getId
		activate BaseType
			BaseType --> CoursesFacade : Long
		deactivate BaseType
		CoursesFacade -> BaseType : getId
		activate BaseType
			BaseType --> CoursesFacade : Long
		deactivate BaseType
		CoursesFacade -> CoursesFacade : register
		activate CoursesFacade
			CoursesFacade --> CoursesFacade : void
		deactivate CoursesFacade
		CoursesFacade --> RegisterCourseController : void
	deactivate CoursesFacade
deactivate RegisterCourseController

@enduml

----