[plantuml,Education.Students.createStudent.puml.png,png]
----
@startuml

participant StudentsRestController
participant StudentsFacade
participant EndpointMapper
participant StudentDto
participant BasePersonDto
participant BaseDto

activate StudentsRestController
	StudentsRestController -> StudentsFacade : create
	activate StudentsFacade
		StudentsFacade --> StudentsRestController : Optional
	deactivate StudentsFacade
	StudentsRestController -> StudentsRestController : resultToDto
	activate StudentsRestController
		StudentsRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> StudentsRestController : StudentDto
		deactivate EndpointMapper
		StudentsRestController --> StudentsRestController : StudentDto
	deactivate StudentsRestController
	StudentsRestController -> StudentDto : toString
	activate StudentDto
		StudentDto -> BasePersonDto : toString
		activate BasePersonDto
			BasePersonDto -> BaseDto : toString
			activate BaseDto
				BaseDto --> BasePersonDto : String
			deactivate BaseDto
			BasePersonDto --> StudentDto : String
		deactivate BasePersonDto
		StudentDto --> StudentsRestController : String
	deactivate StudentDto
deactivate StudentsRestController

@enduml

----