[plantuml,Education.Students.findStudent.puml.png,png]
----
@startuml

participant StudentsRestController
participant EducationFacade
participant EndpointMapper

activate StudentsRestController
	StudentsRestController -> EducationFacade : doActionAndResult
	activate EducationFacade
		EducationFacade -> EducationFacade : educationAction
		activate EducationFacade
			EducationFacade --> EducationFacade : Object
		deactivate EducationFacade
		EducationFacade --> StudentsRestController : Object
	deactivate EducationFacade
	StudentsRestController -> StudentsRestController : resultToDto
	activate StudentsRestController
		StudentsRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> StudentsRestController : StudentDto
		deactivate EndpointMapper
		StudentsRestController --> StudentsRestController : StudentDto
	deactivate StudentsRestController
deactivate StudentsRestController

@enduml

----