[plantuml,Education.RegisterCourse.registerToCourse.puml.png,png]
----
@startuml

participant RegisterCourseController
participant EducationFacade
participant BaseType

activate RegisterCourseController
	RegisterCourseController -> RegisterCourseController : restoreEntity
	activate RegisterCourseController
		RegisterCourseController -> EducationFacade : doActionAndResult
		activate EducationFacade
			EducationFacade -> EducationFacade : educationAction
			activate EducationFacade
				EducationFacade --> EducationFacade : Object
			deactivate EducationFacade
			EducationFacade --> RegisterCourseController : Object
		deactivate EducationFacade
		RegisterCourseController --> RegisterCourseController : Student
	deactivate RegisterCourseController
	RegisterCourseController -> RegisterCourseController : restoreEntity
	activate RegisterCourseController
		RegisterCourseController -> EducationFacade : doActionAndResult
		activate EducationFacade
			EducationFacade -> EducationFacade : educationAction
			activate EducationFacade
				EducationFacade --> EducationFacade : Object
			deactivate EducationFacade
			EducationFacade --> RegisterCourseController : Object
		deactivate EducationFacade
		RegisterCourseController --> RegisterCourseController : Course
	deactivate RegisterCourseController
	RegisterCourseController -> BaseType : getId
	activate BaseType
		BaseType --> RegisterCourseController : Long
	deactivate BaseType
	RegisterCourseController -> BaseType : getId
	activate BaseType
		BaseType --> RegisterCourseController : Long
	deactivate BaseType
	RegisterCourseController -> EducationFacade : doActionAndResult
	activate EducationFacade
		EducationFacade -> EducationFacade : educationAction
		activate EducationFacade
			EducationFacade --> EducationFacade : Object
		deactivate EducationFacade
		EducationFacade --> RegisterCourseController : Object
	deactivate EducationFacade
deactivate RegisterCourseController

@enduml

----