[plantuml,Education.Courses.deleteCourse.puml.png,png]
----
@startuml

participant CoursesRestController
participant EducationFacade

activate CoursesRestController
	CoursesRestController -> CoursesRestController : isInvalid
	activate CoursesRestController
		CoursesRestController --> CoursesRestController : boolean
	deactivate CoursesRestController
	CoursesRestController -> CoursesRestController : delete
	activate CoursesRestController
		CoursesRestController -> EducationFacade : doActionAndResult
		activate EducationFacade
			EducationFacade -> EducationFacade : educationAction
			activate EducationFacade
				EducationFacade --> EducationFacade : Object
			deactivate EducationFacade
			EducationFacade --> CoursesRestController : Object
		deactivate EducationFacade
		CoursesRestController --> CoursesRestController : void
	deactivate CoursesRestController
deactivate CoursesRestController

@enduml

----