[plantuml,Education.Courses.deleteCourse.puml.png,png]
----
@startuml

participant CoursesRestController
participant CoursesFacade

activate CoursesRestController
	CoursesRestController -> CoursesRestController : isInvalid
	activate CoursesRestController
		CoursesRestController --> CoursesRestController : boolean
	deactivate CoursesRestController
	CoursesRestController -> CoursesFacade : delete
	activate CoursesFacade
		CoursesFacade --> CoursesRestController : void
	deactivate CoursesFacade
deactivate CoursesRestController

@enduml

----