[plantuml,Organization.StudentsGroup.delete.puml.png,png]
----
@startuml

participant StudentsGroupsRestController
participant OrganizationFacade

activate StudentsGroupsRestController
	StudentsGroupsRestController -> StudentsGroupsRestController : isInvalid
	activate StudentsGroupsRestController
		StudentsGroupsRestController --> StudentsGroupsRestController : boolean
	deactivate StudentsGroupsRestController
	StudentsGroupsRestController -> StudentsGroupsRestController : deleteStudentsGroupById
	activate StudentsGroupsRestController
		StudentsGroupsRestController -> OrganizationFacade : doActionAndResult
		activate OrganizationFacade
			OrganizationFacade -> OrganizationFacade : organizationAction
			activate OrganizationFacade
				OrganizationFacade --> OrganizationFacade : Object
			deactivate OrganizationFacade
			OrganizationFacade --> StudentsGroupsRestController : Object
		deactivate OrganizationFacade
		StudentsGroupsRestController --> StudentsGroupsRestController : void
	deactivate StudentsGroupsRestController
deactivate StudentsGroupsRestController

@enduml

----