[plantuml,Organization.AuthorityPerson.login.puml.png,png]
----
@startuml

participant AuthorityPersonsRestController
participant AuthorityPersonFacade
participant EndpointMapper

activate AuthorityPersonsRestController
	AuthorityPersonsRestController -> AuthorityPersonFacade : login
	activate AuthorityPersonFacade
		AuthorityPersonFacade --> AuthorityPersonsRestController : Optional
	deactivate AuthorityPersonFacade
	AuthorityPersonsRestController -> AuthorityPersonsRestController : resultToDto
	activate AuthorityPersonsRestController
		AuthorityPersonsRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> AuthorityPersonsRestController : AuthorityPersonDto
		deactivate EndpointMapper
		AuthorityPersonsRestController --> AuthorityPersonsRestController : AuthorityPersonDto
	deactivate AuthorityPersonsRestController
deactivate AuthorityPersonsRestController

@enduml

----