[plantuml,Organization.Faculty.delete.puml.png,png]
----
@startuml

participant FacultiesRestController
participant BaseDto
participant OrganizationFacade

activate FacultiesRestController
	FacultiesRestController -> FacultiesRestController : deleteFaculty
	activate FacultiesRestController
		FacultiesRestController -> BaseDto : getId
		activate BaseDto
			BaseDto --> FacultiesRestController : Long
		deactivate BaseDto
		FacultiesRestController -> FacultiesRestController : deleteFaculty
		activate FacultiesRestController
			FacultiesRestController -> OrganizationFacade : doActionAndResult
			activate OrganizationFacade
				OrganizationFacade -> OrganizationFacade : organizationAction
				activate OrganizationFacade
					OrganizationFacade --> OrganizationFacade : Object
				deactivate OrganizationFacade
				OrganizationFacade --> FacultiesRestController : Object
			deactivate OrganizationFacade
			FacultiesRestController --> FacultiesRestController : void
		deactivate FacultiesRestController
		FacultiesRestController --> FacultiesRestController : void
	deactivate FacultiesRestController
deactivate FacultiesRestController

@enduml

----