[plantuml,Organization.StudentsGroup.findAll.puml.png,png]
----
@startuml

participant StudentsGroupsRestController
participant OrganizationFacade

activate StudentsGroupsRestController
	StudentsGroupsRestController -> StudentsGroupsRestController : findAllStudentsGroups
	activate StudentsGroupsRestController
		StudentsGroupsRestController -> OrganizationFacade : doActionAndResult
		activate OrganizationFacade
			OrganizationFacade -> OrganizationFacade : organizationAction
			activate OrganizationFacade
				OrganizationFacade --> OrganizationFacade : Object
			deactivate OrganizationFacade
			OrganizationFacade --> StudentsGroupsRestController : Object
		deactivate OrganizationFacade
		StudentsGroupsRestController --> StudentsGroupsRestController : Collection
	deactivate StudentsGroupsRestController
	StudentsGroupsRestController -> StudentsGroupsRestController : resultToDto
	activate StudentsGroupsRestController
		StudentsGroupsRestController --> StudentsGroupsRestController : List
	deactivate StudentsGroupsRestController
deactivate StudentsGroupsRestController

@enduml

----