[plantuml,Organization.AuthorityPerson.logout.puml.png,png]
----
@startuml

participant AuthorityPersonsRestController
participant ObjectUtils
participant OrganizationFacade

activate AuthorityPersonsRestController
	AuthorityPersonsRestController -> ObjectUtils : isEmpty
	activate ObjectUtils
		ObjectUtils --> AuthorityPersonsRestController : boolean
	deactivate ObjectUtils
	AuthorityPersonsRestController -> OrganizationFacade : doActionAndResult
	activate OrganizationFacade
		OrganizationFacade -> OrganizationFacade : organizationAction
		activate OrganizationFacade
			OrganizationFacade --> OrganizationFacade : Object
		deactivate OrganizationFacade
		OrganizationFacade --> AuthorityPersonsRestController : Object
	deactivate OrganizationFacade
deactivate AuthorityPersonsRestController

@enduml

----