[plantuml,Organization.AuthorityPerson.login.puml.png,png]
----
@startuml

participant AuthorityPersonsRestController
participant OrganizationFacade
participant EndpointMapper

activate AuthorityPersonsRestController
	AuthorityPersonsRestController -> OrganizationFacade : doActionAndResult
	activate OrganizationFacade
		OrganizationFacade -> OrganizationFacade : organizationAction
		activate OrganizationFacade
			OrganizationFacade --> OrganizationFacade : Object
		deactivate OrganizationFacade
		OrganizationFacade --> AuthorityPersonsRestController : Object
	deactivate OrganizationFacade
	AuthorityPersonsRestController -> AuthorityPersonsRestController : resultToDto
	activate AuthorityPersonsRestController
		AuthorityPersonsRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> AuthorityPersonsRestController : AuthorityPersonDto
		deactivate EndpointMapper
		AuthorityPersonsRestController --> AuthorityPersonsRestController : AuthorityPersonDto
	deactivate AuthorityPersonsRestController
deactivate AuthorityPersonsRestController

@enduml

----