[plantuml,Organization.Faculty.findAll.puml.png,png]
----
@startuml

participant FacultiesRestController
participant OrganizationFacade

activate FacultiesRestController
	FacultiesRestController -> FacultiesRestController : findAllFaculties
	activate FacultiesRestController
		FacultiesRestController -> OrganizationFacade : doActionAndResult
		activate OrganizationFacade
			OrganizationFacade -> OrganizationFacade : organizationAction
			activate OrganizationFacade
				OrganizationFacade --> OrganizationFacade : Object
			deactivate OrganizationFacade
			OrganizationFacade --> FacultiesRestController : Object
		deactivate OrganizationFacade
		FacultiesRestController --> FacultiesRestController : Collection
	deactivate FacultiesRestController
	FacultiesRestController -> FacultiesRestController : resultToDto
	activate FacultiesRestController
		FacultiesRestController --> FacultiesRestController : List
	deactivate FacultiesRestController
deactivate FacultiesRestController

@enduml

----