[plantuml,Organization.Faculty.findById.puml.png,png]
----
@startuml

participant FacultiesRestController
participant OrganizationFacade
participant EndpointMapper

activate FacultiesRestController
	FacultiesRestController -> FacultiesRestController : findFacultyById
	activate FacultiesRestController
		FacultiesRestController -> OrganizationFacade : doActionAndResult
		activate OrganizationFacade
			OrganizationFacade -> OrganizationFacade : organizationAction
			activate OrganizationFacade
				OrganizationFacade --> OrganizationFacade : Object
			deactivate OrganizationFacade
			OrganizationFacade --> FacultiesRestController : Object
		deactivate OrganizationFacade
		FacultiesRestController --> FacultiesRestController : Optional
	deactivate FacultiesRestController
	FacultiesRestController -> FacultiesRestController : resultToDto
	activate FacultiesRestController
		FacultiesRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> FacultiesRestController : FacultyDto
		deactivate EndpointMapper
		FacultiesRestController --> FacultiesRestController : FacultyDto
	deactivate FacultiesRestController
deactivate FacultiesRestController

@enduml

----