[plantuml,Organization.AuthorityPerson.deletePerson.puml.png,png]
----
@startuml

participant AuthorityPersonsRestController
participant OrganizationFacade

activate AuthorityPersonsRestController
	AuthorityPersonsRestController -> AuthorityPersonsRestController : isInvalid
	activate AuthorityPersonsRestController
		AuthorityPersonsRestController --> AuthorityPersonsRestController : boolean
	deactivate AuthorityPersonsRestController
	AuthorityPersonsRestController -> OrganizationFacade : doActionAndResult
	activate OrganizationFacade
		OrganizationFacade -> OrganizationFacade : organizationAction
		activate OrganizationFacade
			OrganizationFacade --> OrganizationFacade : Object
		deactivate OrganizationFacade
		OrganizationFacade --> AuthorityPersonsRestController : Object
	deactivate OrganizationFacade
deactivate AuthorityPersonsRestController

@enduml

----