[plantuml,Organization.StudentsGroup.update.puml.png,png]
----
@startuml

participant StudentsGroupsRestController
participant BaseDto
participant OrganizationFacade
participant EndpointMapper

activate StudentsGroupsRestController
	StudentsGroupsRestController -> BaseDto : getId
	activate BaseDto
		BaseDto --> StudentsGroupsRestController : Long
	deactivate BaseDto
	StudentsGroupsRestController -> StudentsGroupsRestController : isInvalid
	activate StudentsGroupsRestController
		StudentsGroupsRestController --> StudentsGroupsRestController : boolean
	deactivate StudentsGroupsRestController
	StudentsGroupsRestController -> StudentsGroupsRestController : createOrUpdateStudentsGroup
	activate StudentsGroupsRestController
		StudentsGroupsRestController -> OrganizationFacade : doActionAndResult
		activate OrganizationFacade
			OrganizationFacade -> OrganizationFacade : organizationAction
			activate OrganizationFacade
				OrganizationFacade --> OrganizationFacade : Object
			deactivate OrganizationFacade
			OrganizationFacade --> StudentsGroupsRestController : Object
		deactivate OrganizationFacade
		StudentsGroupsRestController --> StudentsGroupsRestController : Optional
	deactivate StudentsGroupsRestController
	StudentsGroupsRestController -> StudentsGroupsRestController : resultToDto
	activate StudentsGroupsRestController
		StudentsGroupsRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> StudentsGroupsRestController : StudentsGroupDto
		deactivate EndpointMapper
		StudentsGroupsRestController --> StudentsGroupsRestController : StudentsGroupDto
	deactivate StudentsGroupsRestController
deactivate StudentsGroupsRestController

@enduml

----