[plantuml,Profile.StudentProfile.update.puml.png,png]
----
@startuml

participant StudentProfileRestController
participant BaseDto
participant PersonProfileFacade
participant EndpointMapper

activate StudentProfileRestController
	StudentProfileRestController -> BaseDto : getId
	activate BaseDto
		BaseDto --> StudentProfileRestController : Long
	deactivate BaseDto
	StudentProfileRestController -> StudentProfileRestController : isInvalid
	activate StudentProfileRestController
		StudentProfileRestController --> StudentProfileRestController : boolean
	deactivate StudentProfileRestController
	StudentProfileRestController -> StudentProfileRestController : createOrUpdateProfile
	activate StudentProfileRestController
		StudentProfileRestController -> PersonProfileFacade : doActionAndResult
		activate PersonProfileFacade
			PersonProfileFacade -> PersonProfileFacade : personProfileAction
			activate PersonProfileFacade
				PersonProfileFacade --> PersonProfileFacade : Object
			deactivate PersonProfileFacade
			PersonProfileFacade --> StudentProfileRestController : Object
		deactivate PersonProfileFacade
		StudentProfileRestController --> StudentProfileRestController : Optional
	deactivate StudentProfileRestController
	StudentProfileRestController -> StudentProfileRestController : toDto
	activate StudentProfileRestController
		StudentProfileRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> StudentProfileRestController : StudentProfileDto
		deactivate EndpointMapper
		StudentProfileRestController --> StudentProfileRestController : StudentProfileDto
	deactivate StudentProfileRestController
deactivate StudentProfileRestController

@enduml

----