[plantuml,Profile.PrincipalProfile.findById.puml.png,png]
----
@startuml

participant PrincipalProfileRestController
participant PersonProfileFacade
participant EndpointMapper

activate PrincipalProfileRestController
	PrincipalProfileRestController -> PrincipalProfileRestController : findPrincipalProfileById
	activate PrincipalProfileRestController
		PrincipalProfileRestController -> PersonProfileFacade : doActionAndResult
		activate PersonProfileFacade
			PersonProfileFacade -> PersonProfileFacade : personProfileAction
			activate PersonProfileFacade
				PersonProfileFacade --> PersonProfileFacade : Object
			deactivate PersonProfileFacade
			PersonProfileFacade --> PrincipalProfileRestController : Object
		deactivate PersonProfileFacade
		PrincipalProfileRestController --> PrincipalProfileRestController : Optional
	deactivate PrincipalProfileRestController
	PrincipalProfileRestController -> PrincipalProfileRestController : toDto
	activate PrincipalProfileRestController
		PrincipalProfileRestController -> EndpointMapper : toDto
		activate EndpointMapper
			EndpointMapper --> PrincipalProfileRestController : PrincipalProfileDto
		deactivate EndpointMapper
		PrincipalProfileRestController --> PrincipalProfileRestController : PrincipalProfileDto
	deactivate PrincipalProfileRestController
deactivate PrincipalProfileRestController

@enduml

----