@startuml

hide footbox
autonumber
actor HttpClient as client
boundary WebApplication as gate
collections RestControllers as controllers
control ConcreteRestController as controller
boundary LinkedBusinessLogicFacade as facade

client -> gate: makes  feature's request
activate gate
gate -> controllers: routes http-request\nto controllers
activate controllers
controllers->controller: using URI routes request\n to concrete controller
deactivate controllers
activate controller
controller->controller: prepares request's data\nfor facade's method call
activate controller
controller->facade: calls facade's method\nwith prepared data
activate facade
deactivate controller
facade-->controller: returns call's result
deactivate facade
activate controller
controller--> controller: prepares http-response
deactivate controller
controller-->gate : sends prepared http-response
deactivate controller
gate --> client: response to request\nwith status and JSON data
deactivate gate

@enduml