@startuml
'https://plantuml.com/class-diagram

!pragma layout smetana

frame Model {
        node education {
            class "StudentDto" as student {
                +id : Long
                +profileId : Long
                +firstName : String
                +lastName : String
                +gender : String
                +description : String
                +courses : List<Course>
            }
            class "CourseDto" as course {
                +id : Long
                +name : String
                +description : String
                +students : List<Student>
            }
        }
        node organization {
            class "AuthorityPersonDto" as principal {
                +id : Long
                +profileId : Long
                +title : String
                +firstName : String
                +lastName : String
                +gender : String
                +description : String
                +courses: List<Faculty>
            }
            class "FacultyDto" as faculty {
                +id : Long
                +name : String
                +dean : AuthorityPerson
                +courses : List<Course>
            }
            class "StudentsGroupDto" as group {
                +id : Long
                +name : String
                +leader : Student
                +students : List<Student>
            }
        }
        node profile {
            abstract class "PersonProfileDto" as baseProfile {
                +id : Long
                +photoUrl : String
                +email : String
                +phone : String
                +location : String
                +extras : Extra[]
            }
            class "PrincipalProfileDto" as principal extends baseProfile {
                +login : String
            }
            class "StudentProfileDto" as stud extends baseProfile{
            }
        }
}
education --[hidden]> organization
'organization --[hidden]> profile

'student --[hidden]> course
'profile <|-- principal
'profile <|-- stud
'student }o-- course
'course }o-- student
'student }o-- group
'course }o-- faculty
'faculty }o-- person
'person ||-- faculty
'person --[hidden]> faculty
'faculty --[hidden]> group
'principal --[hidden]> stud

@enduml