@startuml

hide footbox
autonumber
actor HttpClient as client
boundary WebApplication as gate
collections RestControllers as controllers
control ConcreteRestController as controller
boundary LinkedBusinessLogicFacade as facade

client -> gate: feature's http-request
activate gate
gate -> controllers: route http-request to controllers
activate controllers
controllers->controller: using URI route http-request\n to concrete controller
deactivate controllers
activate controller
controller->controller: prepare request's data\nfor facade's method call
activate controller
controller->facade: calls facade's method\nwith prepared data
activate facade
deactivate controller
facade-->controller: receives call's result
deactivate facade
activate controller
controller--> controller: prepare http-response
deactivate controller
controller-->gate : prepared http-response
deactivate controller
gate --> client: response with status and JSON data
deactivate gate

@enduml